services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cosmetic_shop
      MYSQL_USER: cnweb
      MYSQL_PASSWORD: cnweb
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - springboot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  cosmetic-shop:
    build:
      context: .
      dockerfile: Dockerfile
    image: cosmetic-shop:0.0.1-SNAPSHOT  # pvvinh2003/cosmetic-shop:0.0.1-SNAPSHOT
    container_name: cosmetic-shop
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cosmetic_shop
      SPRING_DATASOURCE_USERNAME: cnweb
      SPRING_DATASOURCE_PASSWORD: cnweb
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  db_data:
